services:
  db:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wallet-local
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet-local
